services:
  grobid:
    image: lfoppiano/grobid:0.8.2
    restart: unless-stopped
    container_name: zotero-grobid
    working_dir: /opt/grobid
    entrypoint:
      - /bin/sh
      - -c
      - |
        ln -sf /opt/grobid/grobid-home/pdfalto/lin-64/pdfalto /opt/grobid/grobid-home/pdfalto/pdfalto
        chmod +x /opt/grobid/grobid-home/pdfalto/lin-64/pdfalto
        exec /tini -s -- ./grobid-service/bin/grobid-service
    ports:
      - "8070:8070"
    environment:
      - JAVA_OPTIONS=-Xms512m -Xmx2g
      - GROBID_TEI_COORDINATES=true
